### ISSUE TITLE
Export to SWMM

### ISSUE THREAD

**Issue by luisbeduschi** [hoettges/QKan#12]
Hi,

I've been trying to export the data from your exercise to SWMM and am getting the following message:

FileNotFoundError: [Errno 2] No such file or directory: '' 
Traceback (most recent call last):
  File "C:\Users/230575/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan\swmmporter\application.py", line 117, in run_export
    self._doexport(db_qkan)
  File "C:\Users/230575/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan\swmmporter\application.py", line 170, in _doexport
    ExportTask(db_qkan, QKan.config.swmm.export_file, QKan.config.swmm.template, QKan.config.selections.teilgebiete, status).run()
  File "C:\Users/230575/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan\swmmporter\_exportSWMM.py", line 104, in run
    self.exportKanaldaten()
  File "C:\Users/230575/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan\swmmporter\_exportSWMM.py", line 184, in exportKanaldaten
    file_to_delete = open(ergfileSwmm, 'w')
FileNotFoundError: [Errno 2] No such file or directory: ''

Any tips of what could I be doing wrong?
Do you have any tutorial or video about the correct procedure to export data from QKan to SWMM correctly?

Thank you for your attention.

Sincerely yours,

Luis Beduschi

**Comment by noblase** [comment]
Hello there, 
sorry for the late response. The issue that you described can appear if you have choosen the export function „add to“(hinzufügen) or „change“(ändern) and not provided a template file. If you choose „new“(neu) the program will produce a new SWMM file with the selected data without specifying a template file.
In the next version of the plugin the issue will not longer occoure, because we have added a template file to the program.
At the moment we do not have a tutorial for the SWMM export.
Best regards,
Nora
