### ISSUE TITLE
Python- Fehler beim SWMM-Export mit Flächen

### ISSUE THREAD

**Issue by schorsch2** [hoettges/QKan#16]
Ich versuche einen SWMM- Export mit Flächen durchzuführen. Dabei erhalte ich einen Python-Fehler:

`2023-12-18T10:04:21     WARNING    Traceback (most recent call last):
              File "C:\Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan\swmmporter\application.py", line 117, in run_export
              self._doexport(db_qkan)
              File "C:\Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan\swmmporter\application.py", line 170, in _doexport
              ExportTask(db_qkan, QKan.config.swmm.export_file, QKan.config.swmm.template, QKan.config.selections.teilgebiete, status).run()
              File "C:\Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan\swmmporter\_exportSWMM.py", line 125, in run
              self.polygons()
              File "C:\Users/wei.IBE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan\swmmporter\_exportSWMM.py", line 1231, in polygons
              xsch = float(liste[x])
             ValueError: could not convert string to float: 'LINESTRING(469762.972888'`

**Comment by noblase** [comment]
Entschuldigung für die späte Rückmeldung. Tritt der Fehler bei den aktuellen QKan Versionen immer noch auf? Ich konnte den Fehler leider nicht reproduzieren.

**Comment by schorsch2** [comment]
Es sieht gut aus, der Fehler tritt in einem neueren Projekt mit der aktuellen Version nicht auf.
