### ISSUE TITLE
AttributeError SWMM object has no attribute dbQK

### ISSUE THREAD

**Issue by schoeller** [hoettges/QKan#7]
Dear all,

thanks for this open source.

After having installed Qkan 3.2.13 through plugin extension manager in Qgis 3.6.10 I created a project (qgs + sqlite) and tried importing the sample file from GisToSwmm5. The subsequent error is thrown:
```
2021-09-01T21:27:29     WARNING    Traceback (most recent call last):
              File "C:\Users/Sebastian Schoeller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan\swmmporter\application.py", line 169, in run
              importKanaldaten(
              File "C:\Users/Sebastian Schoeller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan\swmmporter\importSWMM.py", line 694, in importKanaldaten
              if not swmm.outfalls():
              File "C:\Users/Sebastian Schoeller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qkan\swmmporter\importSWMM.py", line 196, in outfalls
              if not self.dbQK.sql(sql, parameters=(name, elevation, auslasstyp)):
             AttributeError: 'SWMM' object has no attribute 'dbQK'
```
Please find sample files attached.

Kind regards

Sebastian
[qkan_20210901.zip](https://github.com/hoettges/QKan/files/7093847/qkan_20210901.zip)

**Comment by noblase** [comment]
Hello there, sorry for the late response.
In the next QKan release, the SWMM import will be working completely. In the latest updates in the branch qkan3 the SWMM import is also working fine, except it still misses the correct import from polygons. The export from QKan to SWMM is also coming soon. 
Best regards, 
Nora

**Comment by Jannik-Schilling** [comment]
I just had the same problem in version 3.2.34.
